language: android


android:
  components:
    - build-tools-19.1.0

before_install:
  - export TERM=dumb
 - ./gradlew -v
  - uname -a

 # Create and start emulator


#install: gradle clean build

script: ./gradlew clean build
